In [1]:
import numpy as np

In [2]:
a = np.array([100,299,455])
print(type(a))
print(a.shape)
print(a.ndim)
print(a[0],a[1],a[2])


<class 'numpy.ndarray'>
(3,)
1
100 299 455


In [3]:
a[0]=900

In [4]:
print(a)

[900 299 455]


In [5]:
b =np.array([[12,23,45],[90,67,45]])
print(b.shape)
print(b.ndim)
print(b[0,0],b[0,1],b[1,0])


(2, 3)
2
12 23 90


# Numpy :- Add,Sub,Mul :

In [6]:

x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[5,6]])

In [7]:
print(x+y)

# Both print statements are correct:

print(np.add(x,y))

[[ 3  5]
 [ 8 10]]
[[ 3  5]
 [ 8 10]]


In [8]:
print(x-y)

# Both print statements are correct:

print(np.subtract(x,y))

[[-1 -1]
 [-2 -2]]
[[-1 -1]
 [-2 -2]]


In [9]:
print(x*y)

print(np.multiply(x,y))

[[ 2  6]
 [15 24]]
[[ 2  6]
 [15 24]]


# Numpy Dot product:

In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[5,6]])

v = np.array([3,9])
w = np.array([6,5])

print(v.dot(w))  # 1 row and 1 column:

# Both print statement is correct:

print(np.dot(v,w))     

63
63


In [11]:
print(x.dot(v))         # 2 row and 1 column:

# Both print statements are correct:

print(np.dot(x,v))

[21 45]
[21 45]


In [12]:
print(x.dot(y))         # 2 row and 2 column:

# Both print statements are correct:

print(np.dot(x,y))

[[12 15]
 [26 33]]
[[12 15]
 [26 33]]


# Numpy Slicing:

In [13]:
a = np.array([1,2,3])   # 1D array using numpy:

In [14]:
print(a)

[1 2 3]


In [15]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,70,4,2]])     # 2D array using numpy:

In [16]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 70  4  2]]


In [17]:
b =a[:2, :2]    #for 2 row and 2 column / 1st slicing shows row and 2nd slicing shows columns

In [18]:
print(b)

[[1 2]
 [5 6]]


In [19]:
b[[0,0],[0,1]]

array([1, 2])

In [20]:
b[0,0] = 34

In [21]:
b

array([[34,  2],
       [ 5,  6]])

In [22]:
print(a[0,1],'\n')

2 



In [23]:
b[0,1]

2

In [24]:
print(b)

[[34  2]
 [ 5  6]]


In [25]:
print(a)

[[34  2  3  4]
 [ 5  6  7  8]
 [ 9 70  4  2]]


# Reshaping an array:

In [26]:
a

array([[34,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 70,  4,  2]])

In [27]:
a.shape

(3, 4)

In [28]:
a.ndim

2

 Numpy also provide a reshape function to resize an array:

In [29]:
b = a.reshape(4,3)

In [30]:
b

array([[34,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [70,  4,  2]])

# creating an empty array:

In [31]:
a = np.empty([2,3],dtype = int)

In [32]:
a

array([[12, 23, 45],
       [90, 67, 45]])

# creating array filled with 0's:

In [33]:
a = np.zeros(6)

In [34]:
a

array([0., 0., 0., 0., 0., 0.])

In [35]:
a =np.zeros([4,3],dtype = int)  # data type is imp to define otherwise default data type is float :

In [36]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Creating array filled with 1's:

In [37]:
a = np.ones(6)

In [38]:
a

array([1., 1., 1., 1., 1., 1.])

In [39]:
a = np.ones([4,3],dtype = int)

In [40]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Mixing integer indexing and slicing indexing:

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,70,4,2]])     # 2D array using numpy:

In [42]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 70,  4,  2]])

In [43]:
row_r1 = a[1,:]          # It will give 1D array:

In [44]:
row_r1                  

array([5, 6, 7, 8])

In [45]:
row_r2 = a[1:2, :]      # It will give 2D array:

In [46]:
row_r2

array([[5, 6, 7, 8]])

In [47]:
print(row_r1,row_r1.shape)

[5 6 7 8] (4,)


In [48]:
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


# We can make same distinction when accessing columns of an array:

In [49]:
col_c1 = a[:, 1]  # It will gives 1D array;

In [50]:
col_c1

array([ 2,  6, 70])

In [51]:
col_c2 = a[:, 1:2]      #It will gives 2D array:

In [52]:
col_c2

array([[ 2],
       [ 6],
       [70]])

In [53]:
b = a[1:,1:3]

In [54]:
b

array([[ 6,  7],
       [70,  4]])

In [55]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 70,  4,  2]])

In [56]:
a.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [70,  4,  2]]])

# Numpy array indexing:

In [57]:
a = np.array([[1,2],[3,4],[5,6]])

In [58]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
print(a[[0,1,2],[1,1,0]])

[2 4 5]


In [60]:
#Or

print(np.array([a[0,1],a[1,1],a[2,0]]))

[2 4 5]


In [61]:
print(a[[0,1],[1,1]])

[2 4]


In [62]:
#Or

print(np.array(a[[0,1],[1,1]]))

[2 4]


# More array indexing:

In [63]:
b = np.array([[23,45,67,89],[12,34,56,89],[23,12,45,98],[90,78,67,56]])

In [64]:
b

array([[23, 45, 67, 89],
       [12, 34, 56, 89],
       [23, 12, 45, 98],
       [90, 78, 67, 56]])

In [65]:
print(b.shape)

(4, 4)


In [66]:
print(b.ndim)

2


Create an array of indices:

In [67]:
c = np.array([0, 2 ,0 ,1])   #(0,1,2,3),([0,2,0,1])

In [68]:
print(b[np.arange(4),c])

[23 56 23 78]


In [69]:
b[np.arange(4),c]+= 10

In [70]:
print(b)

[[33 45 67 89]
 [12 34 66 89]
 [33 12 45 98]
 [90 88 67 56]]


# Boolean array indexing:

In [71]:
 a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
bool_index =(a<2)

In [73]:
bool_index

array([[ True, False],
       [False, False],
       [False, False]])

In [74]:
print(a[bool_index])

[1]


In [75]:
#Or

print(a[a<2])

[1]


# Numpy sum:

In [76]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
print(np.sum(a))

21


In [78]:
print(np.sum(a, axis=0))   # axis = 0 for column:

[ 9 12]


In [79]:
print(np.sum(a, axis = 1))

[ 3  7 11]


# Numpy reshape using arange:

In [80]:
a =np.arange(8)

In [81]:
print("Orignal array : \n",a)

Orignal array : 
 [0 1 2 3 4 5 6 7]


In [82]:
a =np.arange(4).reshape(2,2)

print(a)

[[0 1]
 [2 3]]


In [83]:
a =np.arange(8).reshape(4,2)

print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


construct 3D array:

In [84]:
a = np.arange(8).reshape(2,2,2)

print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# Numpy Tensors 1D,2D,3D:

A tensor that contains only one numbers is called scaler(or scaler tensor,or 0-D tensor).

In numpy, a float32 or float64 is a scaler tensor(or scaler array)

In [85]:
a = np.array(12)
print(a,[a.ndim])

12 [0]


An array of numbers is called vector, or 1D tensor.

 A 1D tensor is said to have exactly one axis.Following is a numpy vector.

In [86]:
a =np.array([12,23,45])
print(a,[a.ndim])

[12 23 45] [1]


In [87]:
# Matrices
# An array of vectors is a matrix, or 2D tensor.
# A matrix has two axis(often referred to row and columns).

In [88]:
a = np.array([[12,23,45,67],
            [23,56,89,90],
            [12,34,78,9]])

In [89]:
print([a.ndim])

[2]


# Numpy Transposing:

In [90]:
a = np.array([[1,2],[3,4]])

In [91]:
a

array([[1, 2],
       [3, 4]])

In [92]:
print(a.T)

[[1 3]
 [2 4]]


In [93]:
b = np.array([1,4,6,8])   # For 1D array Trnasposing is not works.

In [94]:
print(b.T)     

[1 4 6 8]


# Numpy Broadcasting:

In [95]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[12,34,5]])
v = np.array([1,4,5])
y = np.empty_like(x)

Add the vertex v to each row of the matrix x with an explicit loop.

In [96]:
for i in range(4):
    y[i,:] = x[i,:]+v
print(y)    

[[ 2  6  8]
 [ 5  9 11]
 [ 8 12 14]
 [13 38 10]]


In [97]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[12,34,5]])
v = np.array([1,4,5])
y = x+v

In [98]:
print(y)

[[ 2  6  8]
 [ 5  9 11]
 [ 8 12 14]
 [13 38 10]]


# Ways of Creating arrays in numpy:

1. array()
2. linspace()
3. logspace()
4. arange()
5. zeros()
6. ones()

In [99]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Or

In [100]:
from numpy import*
a = array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int32


In [101]:
a =np.array([1,2,3,5.9])
print(a,[a.dtype])

[1.  2.  3.  5.9] [dtype('float64')]


In [102]:
a =np.array([1,2,3,5.9],int)
print(a,[a.dtype])

[1 2 3 5] [dtype('int32')]


# 2. linspace(start,stop,step)

In [103]:
a = linspace(2,10,5)
print(a)

[ 2.  4.  6.  8. 10.]


# 3. arange(start,last,step)

In [104]:
a = arange(0,15,2)
print(a)

[ 0  2  4  6  8 10 12 14]


# 4. logspace(start,stop,parts)

In [105]:
a = logspace(1,20,5)
print(a)

[1.00000000e+01 5.62341325e+05 3.16227766e+10 1.77827941e+15
 1.00000000e+20]


# 5. zeros()

In [106]:
a = zeros(6,int)
print(a)

[0 0 0 0 0 0]


In [107]:
a = zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


# 6. Ones()

In [108]:
a = ones(6,int)
print(a)

[1 1 1 1 1 1]


In [109]:
a = ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


# we can also find sin(array),cos(array),log(array),sqrt(array) :

In [110]:
a = np.array([1,2,3,4,5])
print(sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [111]:
print(cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [112]:
print(log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [113]:
print(sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


# We can also use sum(),min(),max(),sort() :

In [114]:
a = array([1,2,3])
b = array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [115]:
a = array([1,2,3])
a = a+5
print(a)

[6 7 8]


In [116]:
a = array([1,4,5,6,7])
print(sum(a))

23


In [117]:
a = array([1,4,5,6,7])
print(min(a))

1


In [118]:
a = array([1,4,5,6,7])
print(max(a))

7


In [119]:
a = array([9,4,5,8,7])
print(sort(a))

[4 5 7 8 9]


In [120]:
a = array([1,2,3,4])
b = a
print(a)
print(b)
print(id(a))       # Both a and b preferred to same location.
print(id(b))

[1 2 3 4]
[1 2 3 4]
819950884784
819950884784


# view()

view() is a function which is used to create new array in different location.

In [121]:
a = array([1,2,3,4])
b = a.view()
print(a)
print(b)
print(id(a))
print(id(b))

[1 2 3 4]
[1 2 3 4]
819950888000
819950890400


There are two types of copies n array:-

1.shallow copy()

2.Deep copy()

# 1. shallow copy()

In [122]:
a = array([2,4,5,6])
b = a.view()                       # In shallow copy we can use view() means changes perfrom 1st as same copy in 2nd. 
a[1] = 7
print(a)
print(id(a))                       # id are also same.
print(b)
print(id(b))

[2 7 5 6]
819950909360
[2 7 5 6]
819950910080


# 2. Deep copy()

In [123]:
a = array([2,4,5,6])
b = a.copy()                       # In Deep copy we can use copy() means changes perfrom 1st as same copy in 2nd. 
a[1] = 7
print(a)
print(id(a))                     # id are also different.
print(b)
print(id(b))

[2 7 5 6]
819950944864
[2 4 5 6]
819950944944


# Working with matrix in python using numpy:

In [124]:
a =array([[1,2,3,4],
          [5,6,7,9]])
print(a)

[[1 2 3 4]
 [5 6 7 9]]


# dtype:

In [125]:
print(a.dtype)

int32


# ndim:

In [126]:
print(a.ndim)

2


# shape :

In [127]:
print(a.shape)

(2, 4)


# size :

In [128]:
print(a.size)

8


# flatten() :

In [129]:
a = array([[1,2,3],
          [4,5,6]])
b = a.flatten()
print(a)

print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# reshape():

In [130]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [133]:
a = array([[2,4,6,8],
        [1,3,5,7]])
m = matrix(a)
print(m)

[[2 4 6 8]
 [1 3 5 7]]


# Or :

In [134]:
m = matrix('1 2 3 4;5 6 7 8')
print(m)


[[1 2 3 4]
 [5 6 7 8]]


In [135]:
m.min(axis = 1)    # 1 for column:

matrix([[1],
        [5]])

In [136]:
m.min(axis = 0)    # 0 for row:

matrix([[1, 2, 3, 4]])

In [137]:
print(diagonal(m))

[1 6]


In [138]:
print(m.min())

1


In [139]:
print(m.max())

8


In [140]:
m1 = matrix('1 2 3 4;5 6 7 8')
m2 = matrix('3 1 8 9;0 2 5 6')
m3 = m1+m2
print(m1)
print(m2)
print(m3)

[[1 2 3 4]
 [5 6 7 8]]
[[3 1 8 9]
 [0 2 5 6]]
[[ 4  3 11 13]
 [ 5  8 12 14]]


In [141]:
m1 = matrix('1 2 3 4;5 6 7 8')
m2 = matrix('3 1 8 9;0 2 5 6')
m3 = m1+m2
print(m1)
print(m2)
print(m3)

[[1 2 3 4]
 [5 6 7 8]]
[[3 1 8 9]
 [0 2 5 6]]
[[ 4  3 11 13]
 [ 5  8 12 14]]
